version: '3'

services:
  app:
    image: compmoto-app
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - compmoto-net

  postgres: 
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=compmoto_dev
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - compmoto-net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - compmoto-net
    command: ["./wait-for-it.sh", "app:3000", "--", "nginx", "-g", "daemon off;"]

networks:
  compmoto-net:
    driver: bridge
