version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: compmoto-app
    volumes:
      - .:/app:delegated  # Use 'delegated' for better performance on Mac/Windows
    ports:
      - "3000:3000" 
    networks:
      - compmoto-net
    env_file:
      - .env
    environment:
      PRISMA_LOG_LEVEL: query,error,info,warn  # Pass log level as environment variable
  postgres: 
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: compmoto_dev
      POSTGRES_USER: compmoto_dev
      POSTGRES_PASSWORD: compmoto_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - compmoto-net
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - compmoto-net
networks:
  compmoto-net:
    driver: bridge
volumes:
  postgres_data: