services:
  app:
    image: compmoto-app
    build:
      context: ./
      # target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app # This line might be redundant (see note below) 
      - /app/node_modules
      - /app/.next
      - ./logs:/app/logs # Mount host logs directory to container
    ports:
      - "3000:3000" 
    networks:
      - compmoto-net
    env_file:
      - .env
  postgres: 
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: compmoto_dev
      POSTGRES_USER: compmoto_dev
      POSTGRES_PASSWORD: compmoto_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - compmoto-net
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - compmoto-net
networks:
  compmoto-net:
    driver: bridge
volumes:
  postgres_data: