import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../styles/fonts.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Compmoto Portal",
  description: "Generated by Mony",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen default-font">{children}</body>
    </html>
  );
}
