import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.scss";
import "../../styles/fonts.scss";
import Layout from "@components/layout";
import Head from "next/head";
import i18nConfig from "../../i18nConfig";
import { dir } from "i18next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Compmoto Portal",
  description: "Generated by Mony",
};



export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default async function RootLayout({
  children,
  params: { locale } // Provide a default value for 'locale'
}: RootLayoutProps) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${inter.className} min-h-screen default-font`}>
        <Layout children={children}/>
      </body>
    </html>
    
  );
}